services:
  fzfetch:
    image: ghcr.io/zhpjy/fzfetch
    ports:
      - "3000:3000"
    volumes:
      - ./your-folder1:/files/your-folder1
      - ./your-folder2:/files/your-folder2
      - fzfetch-data:/data
    restart: unless-stopped

volumes:
  fzfetch-data:
